samples:
    SC173863_ACCTCCAA_L008_R2_001_HQ_paired: /sc/arion/projects/canan/data_ahuno/CRC_PR_03192021/fastq/DrMarciaCruz_WES_CRC_EarlyOnset/Tumor/test_pipelines/SC173863_ACCTCCAA_L008_R2_001_HQ_paired.fastq.gz
    SC173866_CTGGCATA_L004_R1_001_HQ_paired: /sc/arion/projects/canan/data_ahuno/CRC_PR_03192021/fastq/DrMarciaCruz_WES_CRC_EarlyOnset/Tumor/test_pipelines/SC173866_CTGGCATA_L004_R1_001_HQ_paired.fastq.gz
